[package]
name = "libinjection-rs"
version = "0.3.1"
authors = ["Paul Callahan <paul@tcell.io>"]
auto-build-binaries = true

[dependencies]
libc = "0.2.40"
phf = "0.7.22"
phf_codegen = "0.7.22"

[lib]
name = "injection"
crate-type = ["cdylib", "lib"]
